#!/usr/bin/env python
import shutil

from lib.na_constants import HOSTS_DB, VGROUP
from lib.util import exec_cmd


def ssd_reset():
    exec_cmd('vgremove -f {}'.format(VGROUP), quiet=True)
    exec_cmd('modprobe -r brd')
    shutil.unlink(HOSTS_DB)


if __name__ == '__main__':
    ssd_reset()
