#!/usr/bin/env python
from lib.na_constants import VGROUP
from lib.util import exec_cmd


def ssd_reset():
    exec_cmd('vgremove -f {}'.format(VGROUP), quiet=True)
    exec_cmd('modprobe -r brd')


if __name__ == '__main__':
    ssd_reset()
